# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 40e5a34
_src_path: gh:liblaf/copier-python
author: liblaf
email: 30631553+liblaf@users.noreply.github.com
license: MIT
name: physics-toolkit
owner: liblaf
repo: physics-toolkit
